# Generated by Django 5.2.13 on 2026-04-14 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='orgstructure.orgunit')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrgUnitMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255)),
                ('is_lead', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='orgstructure.orgunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_unit_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_lead', 'user_id'),
            },
        ),
        migrations.CreateModel(
            name='UserManagerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_links', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_reports_links', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_links', to='organizations.organization')),
            ],
            options={
                'ordering': ('employee_id',),
            },
        ),
        migrations.AddConstraint(
            model_name='orgunit',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_org_unit_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='orgunitmember',
            constraint=models.UniqueConstraint(fields=('org_unit', 'user'), name='uniq_org_unit_member'),
        ),
        migrations.AddConstraint(
            model_name='usermanagerlink',
            constraint=models.UniqueConstraint(fields=('organization', 'employee'), name='uniq_manager_link_per_employee_org'),
        ),
    ]
