# Generated by Django 5

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgstructure", "0002_career_events_and_assigned_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunit",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
