# Generated by Django 5.2.13 on 2026-04-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgstructure', '0003_orgunit_description'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeecareerevent',
            new_name='orgstructur_employe_0076b5_idx',
            old_name='orgstruct_career_emp_idx',
        ),
        migrations.RenameIndex(
            model_name='employeecareerevent',
            new_name='orgstructur_event_t_4e1e15_idx',
            old_name='orgstruct_career_evt_idx',
        ),
        migrations.RenameIndex(
            model_name='employeecareerevent',
            new_name='orgstructur_project_758398_idx',
            old_name='orgstruct_career_proj_idx',
        ),
        migrations.RenameIndex(
            model_name='employeecareerevent',
            new_name='orgstructur_org_uni_4a5416_idx',
            old_name='orgstruct_career_ou_idx',
        ),
    ]
