# Generated by Django 5.2.13 on 2026-04-21 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgstructure', '0001_initial'),
        ('projects', '0002_alter_project_status_alter_projectmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_projects', to='orgstructure.orgunit'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='contribution_note',
            field=models.CharField(blank=True, help_text='e.g. part-time with another department lead', max_length=255),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='engagement_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
