# Generated by Django 5.2.13 on 2026-04-23 09:35

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.projects.models.project_document_upload_to),
        ),
    ]
