# Generated by Django 5.2.13 on 2026-04-28 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectmember_is_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectresourcerequest',
            name='projects_pr_stat_created_idx',
        ),
        migrations.RenameIndex(
            model_name='projectresourcerequest',
            new_name='projects_pr_project_2c5334_idx',
            old_name='projects_pr_proj_stat_idx',
        ),
        migrations.AddIndex(
            model_name='projectresourcerequest',
            index=models.Index(fields=['status', '-created_at'], name='projects_pr_status_817559_idx'),
        ),
    ]
