from django.urls import path

from apps.identity.api.views import (
    AuthCsrfCookieView,
    AuthLoginView,
    AuthLogoutView,
    AuthSessionView,
    InviteActivateView,
)
from apps.projects.api.views import (
    ProjectArchiveView,
    ProjectDetailView,
    ProjectListView,
    ProjectMemberDetailView,
    ProjectMembersView,
    ProjectResourceRequestCompanyListView,
    ProjectResourceRequestCreateView,
    ProjectResourceRequestResolveView,
    ProjectRestoreView,
)
from apps.workspaces.api.views import (
    BuildingDepartmentsView,
    BuildingDetailView,
    BuildingsListView,
    EmployeeMeProfileView,
    EmployeeProfileByIdView,
    EmployeeProfileGlobalAliasView,
    EmployeeProfileView,
    EmployeeWorkspaceCabinetView,
    EmployeeWorkspaceContextView,
    FloorWorkspaceView,
    WorkspaceTaskAliasDetailView,
    WorkspaceTaskAuditView,
    WorkspaceTaskChecklistItemView,
    WorkspaceTaskChecklistView,
    WorkspaceTaskCommentsView,
    WorkspaceTasksAliasView,
    WorkspaceQuickTasksView,
    WorkspaceTaskBuildingAuditView,
    WorkspaceTaskBuildingChecklistItemView,
    WorkspaceTaskBuildingChecklistView,
    WorkspaceTaskBuildingCommentsView,
    WorkspaceContextAliasView,
    WorkspaceContextGlobalAliasView,
)

from apps.orgstructure.api.company_admin_departments import (
    CompanyAdminDepartmentDetailView,
    CompanyAdminDepartmentLeadView,
    CompanyAdminDepartmentsView,
)

from .parallel_contract_views import (
    AdminActionDetailView,
    AdminActionEventsView,
    AdminActionStatsView,
    CompanyAdminInviteRevokeView,
    CompanyAdminInvitesView,
    CompanyAdminOverviewView,
    CompanyAdminUserRoleUpdateView,
    CompanyAdminUsersView,
    PlatformAuditEventsView,
    PlatformAuditExportView,
    PlatformAuditStatsView,
    PlatformInviteRevokeView,
    PlatformInvitesView,
    PlatformOverviewView,
    PlatformTenantsView,
    PlatformTenantStatusView,
    PlatformUsersView,
    TaskActivityView,
    TaskDetailView,
    TasksBoardView,
    TasksBulkAssignView,
    TasksBulkStatusView,
    TasksStatsView,
    TasksView,
)

urlpatterns = [
    path("auth/csrf", AuthCsrfCookieView.as_view()),
    path("auth/login", AuthLoginView.as_view()),
    path("auth/logout", AuthLogoutView.as_view()),
    path("auth/session", AuthSessionView.as_view()),
    path("auth/invite/activate", InviteActivateView.as_view()),
    path("buildings", BuildingsListView.as_view()),
    path("buildings/<str:building_id>", BuildingDetailView.as_view()),
    path("buildings/<str:building_id>/departments", BuildingDepartmentsView.as_view()),
    path("buildings/<str:building_id>/floors/<str:floor_id>/workspace", FloorWorkspaceView.as_view()),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/workspace/employee/<str:employee_id>",
        EmployeeWorkspaceContextView.as_view(),
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/employees/<str:employee_id>/profile",
        EmployeeProfileView.as_view(),
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/tasks/<str:task_id>/audit",
        WorkspaceTaskBuildingAuditView.as_view(),
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/tasks/<str:task_id>/comments",
        WorkspaceTaskBuildingCommentsView.as_view(),
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/tasks/<str:task_id>/checklist",
        WorkspaceTaskBuildingChecklistView.as_view(),
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/tasks/<str:task_id>/checklist/<str:item_id>",
        WorkspaceTaskBuildingChecklistItemView.as_view(),
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/workspace-context",
        WorkspaceContextAliasView.as_view(),
    ),
    path("workspace/context", WorkspaceContextGlobalAliasView.as_view()),
    path("employees/<str:employee_id>/profile", EmployeeProfileGlobalAliasView.as_view()),
    path("workspace", EmployeeWorkspaceCabinetView.as_view()),
    path("workspace/tasks", WorkspaceTasksAliasView.as_view()),
    path("workspace/tasks/<str:task_id>/audit", WorkspaceTaskAuditView.as_view()),
    path("workspace/tasks/<str:task_id>/comments", WorkspaceTaskCommentsView.as_view()),
    path("workspace/tasks/<str:task_id>/checklist", WorkspaceTaskChecklistView.as_view()),
    path("workspace/tasks/<str:task_id>/checklist/<str:item_id>", WorkspaceTaskChecklistItemView.as_view()),
    path("workspace/tasks/<str:task_id>", WorkspaceTaskAliasDetailView.as_view()),
    path("employees/me", EmployeeMeProfileView.as_view()),
    path("employees/<str:employee_id>", EmployeeProfileByIdView.as_view()),
    path("workspace/quick-tasks", WorkspaceQuickTasksView.as_view()),
    path("projects/resource-requests", ProjectResourceRequestCompanyListView.as_view()),
    path(
        "projects/resource-requests/<int:request_id>/resolve",
        ProjectResourceRequestResolveView.as_view(),
    ),
    path("projects", ProjectListView.as_view()),
    path("projects/<int:pk>", ProjectDetailView.as_view()),
    path("projects/<int:pk>/archive", ProjectArchiveView.as_view()),
    path("projects/<int:pk>/restore", ProjectRestoreView.as_view()),
    path("projects/<int:pk>/members", ProjectMembersView.as_view()),
    path("projects/<int:pk>/members/<int:member_id>", ProjectMemberDetailView.as_view()),
    path("projects/<int:pk>/resource-requests", ProjectResourceRequestCreateView.as_view()),
    path("company/admin/overview", CompanyAdminOverviewView.as_view()),
    path("company/admin/departments", CompanyAdminDepartmentsView.as_view()),
    path(
        "company/admin/departments/<int:department_id>",
        CompanyAdminDepartmentDetailView.as_view(),
    ),
    path(
        "company/admin/departments/<int:department_id>/lead",
        CompanyAdminDepartmentLeadView.as_view(),
    ),
    path("company/admin/users", CompanyAdminUsersView.as_view()),
    path("company/admin/invites", CompanyAdminInvitesView.as_view()),
    path("company/admin/users/<int:user_id>/role", CompanyAdminUserRoleUpdateView.as_view()),
    path("company/admin/invites/<int:invite_id>/revoke", CompanyAdminInviteRevokeView.as_view()),
    path("admin/platform/overview", PlatformOverviewView.as_view()),
    path("admin/platform/tenants", PlatformTenantsView.as_view()),
    path("admin/platform/users", PlatformUsersView.as_view()),
    path("admin/platform/invites", PlatformInvitesView.as_view()),
    path("admin/platform/tenants/<int:tenant_id>/status", PlatformTenantStatusView.as_view()),
    path("admin/platform/invites/<int:invite_id>/revoke", PlatformInviteRevokeView.as_view()),
    path("admin/platform/audit/stats", PlatformAuditStatsView.as_view()),
    path("admin/platform/audit/events", PlatformAuditEventsView.as_view()),
    path("admin/platform/audit/export", PlatformAuditExportView.as_view()),
    path("admin/actions/stats", AdminActionStatsView.as_view()),
    path("admin/actions/events", AdminActionEventsView.as_view()),
    path("admin/actions/events/<int:action_id>", AdminActionDetailView.as_view()),
    path("tasks", TasksView.as_view()),
    path("tasks/board", TasksBoardView.as_view()),
    path("tasks/stats", TasksStatsView.as_view()),
    path("tasks/bulk/status", TasksBulkStatusView.as_view()),
    path("tasks/bulk/assign", TasksBulkAssignView.as_view()),
    path("tasks/<int:task_id>/activity", TaskActivityView.as_view()),
    path("tasks/<int:task_id>", TaskDetailView.as_view()),
]
