from django.urls import path

from apps.identity.api.views import AuthLoginView, AuthLogoutView, AuthSessionView, InviteActivateView
from apps.projects.api.views import (
    ProjectArchiveView,
    ProjectDetailView,
    ProjectListView,
    ProjectMemberDetailView,
    ProjectMembersView,
    ProjectRestoreView,
)
from apps.workspaces.api.views import (
    BuildingDepartmentsView,
    BuildingDetailView,
    BuildingsListView,
    EmployeeProfileGlobalAliasView,
    EmployeeProfileView,
    EmployeeWorkspaceContextView,
    FloorWorkspaceView,
    WorkspaceContextAliasView,
    WorkspaceContextGlobalAliasView,
)

from .parallel_contract_views import (
    AdminActionDetailView,
    AdminActionEventsView,
    AdminActionStatsView,
    CompanyAdminDepartmentsView,
    CompanyAdminInviteRevokeView,
    CompanyAdminInvitesView,
    CompanyAdminOverviewView,
    CompanyAdminUserRoleUpdateView,
    CompanyAdminUsersView,
    PlatformAuditEventsView,
    PlatformAuditExportView,
    PlatformAuditStatsView,
    PlatformInviteRevokeView,
    PlatformInvitesView,
    PlatformOverviewView,
    PlatformTenantsView,
    PlatformTenantStatusView,
    PlatformUsersView,
    TaskActivityView,
    TaskDetailView,
    TasksBoardView,
    TasksBulkAssignView,
    TasksBulkStatusView,
    TasksStatsView,
    TasksView,
)

urlpatterns = [
    path("auth/login", AuthLoginView.as_view()),
    path("auth/logout", AuthLogoutView.as_view()),
    path("auth/session", AuthSessionView.as_view()),
    path("auth/invite/activate", InviteActivateView.as_view()),
    path("buildings", BuildingsListView.as_view()),
    path("buildings/<str:building_id>", BuildingDetailView.as_view()),
    path("buildings/<str:building_id>/departments", BuildingDepartmentsView.as_view()),
    path("buildings/<str:building_id>/floors/<str:floor_id>/workspace", FloorWorkspaceView.as_view()),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/workspace/employee/<str:employee_id>",
        EmployeeWorkspaceContextView.as_view(),
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/employees/<str:employee_id>/profile",
        EmployeeProfileView.as_view(),
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/workspace-context",
        WorkspaceContextAliasView.as_view(),
    ),
    path("workspace/context", WorkspaceContextGlobalAliasView.as_view()),
    path("employees/<str:employee_id>/profile", EmployeeProfileGlobalAliasView.as_view()),
    path("projects", ProjectListView.as_view()),
    path("projects/<int:pk>", ProjectDetailView.as_view()),
    path("projects/<int:pk>/archive", ProjectArchiveView.as_view()),
    path("projects/<int:pk>/restore", ProjectRestoreView.as_view()),
    path("projects/<int:pk>/members", ProjectMembersView.as_view()),
    path("projects/<int:pk>/members/<int:member_id>", ProjectMemberDetailView.as_view()),
    path("company/admin/overview", CompanyAdminOverviewView.as_view()),
    path("company/admin/departments", CompanyAdminDepartmentsView.as_view()),
    path("company/admin/users", CompanyAdminUsersView.as_view()),
    path("company/admin/invites", CompanyAdminInvitesView.as_view()),
    path("company/admin/users/<int:user_id>/role", CompanyAdminUserRoleUpdateView.as_view()),
    path("company/admin/invites/<int:invite_id>/revoke", CompanyAdminInviteRevokeView.as_view()),
    path("admin/platform/overview", PlatformOverviewView.as_view()),
    path("admin/platform/tenants", PlatformTenantsView.as_view()),
    path("admin/platform/users", PlatformUsersView.as_view()),
    path("admin/platform/invites", PlatformInvitesView.as_view()),
    path("admin/platform/tenants/<int:tenant_id>/status", PlatformTenantStatusView.as_view()),
    path("admin/platform/invites/<int:invite_id>/revoke", PlatformInviteRevokeView.as_view()),
    path("admin/platform/audit/stats", PlatformAuditStatsView.as_view()),
    path("admin/platform/audit/events", PlatformAuditEventsView.as_view()),
    path("admin/platform/audit/export", PlatformAuditExportView.as_view()),
    path("admin/actions/stats", AdminActionStatsView.as_view()),
    path("admin/actions/events", AdminActionEventsView.as_view()),
    path("admin/actions/events/<int:action_id>", AdminActionDetailView.as_view()),
    path("tasks", TasksView.as_view()),
    path("tasks/board", TasksBoardView.as_view()),
    path("tasks/stats", TasksStatsView.as_view()),
    path("tasks/bulk/status", TasksBulkStatusView.as_view()),
    path("tasks/bulk/assign", TasksBulkAssignView.as_view()),
    path("tasks/<int:task_id>/activity", TaskActivityView.as_view()),
    path("tasks/<int:task_id>", TaskDetailView.as_view()),
]
