from django.urls import path

from .parallel_contract_views import (
    AdminActionDetailView,
    AdminActionEventsView,
    AdminActionStatsView,
    CompanyAdminDepartmentsView,
    CompanyAdminInviteRevokeView,
    CompanyAdminInvitesView,
    CompanyAdminOverviewView,
    CompanyAdminUserRoleUpdateView,
    CompanyAdminUsersView,
    PlatformAuditEventsView,
    PlatformAuditExportView,
    PlatformAuditStatsView,
    PlatformInviteRevokeView,
    PlatformInvitesView,
    PlatformOverviewView,
    PlatformTenantsView,
    PlatformTenantStatusView,
    PlatformUsersView,
    TasksBulkAssignView,
    TasksBoardView,
    TasksBulkStatusView,
    TaskActivityView,
    TaskDetailView,
    TasksStatsView,
    TasksView,
)

urlpatterns = [
    path("company/admin/overview", CompanyAdminOverviewView.as_view()),
    path("company/admin/departments", CompanyAdminDepartmentsView.as_view()),
    path("company/admin/users", CompanyAdminUsersView.as_view()),
    path("company/admin/invites", CompanyAdminInvitesView.as_view()),
    path("company/admin/users/<int:user_id>/role", CompanyAdminUserRoleUpdateView.as_view()),
    path("company/admin/invites/<int:invite_id>/revoke", CompanyAdminInviteRevokeView.as_view()),
    path("admin/company/overview", CompanyAdminOverviewView.as_view()),
    path("admin/company/departments", CompanyAdminDepartmentsView.as_view()),
    path("admin/company/users", CompanyAdminUsersView.as_view()),
    path("admin/company/invites", CompanyAdminInvitesView.as_view()),
    path("admin/company/users/<int:user_id>/role", CompanyAdminUserRoleUpdateView.as_view()),
    path("admin/company/invites/<int:invite_id>/revoke", CompanyAdminInviteRevokeView.as_view()),
    path("admin/platform/overview", PlatformOverviewView.as_view()),
    path("admin/platform/tenants", PlatformTenantsView.as_view()),
    path("admin/platform/users", PlatformUsersView.as_view()),
    path("admin/platform/invites", PlatformInvitesView.as_view()),
    path("admin/platform/tenants/<int:tenant_id>/status", PlatformTenantStatusView.as_view()),
    path("admin/platform/invites/<int:invite_id>/revoke", PlatformInviteRevokeView.as_view()),
    path("platform/admin/overview", PlatformOverviewView.as_view()),
    path("platform/admin/tenants", PlatformTenantsView.as_view()),
    path("platform/admin/users", PlatformUsersView.as_view()),
    path("platform/admin/invites", PlatformInvitesView.as_view()),
    path("platform/admin/tenants/<int:tenant_id>/status", PlatformTenantStatusView.as_view()),
    path("platform/admin/invites/<int:invite_id>/revoke", PlatformInviteRevokeView.as_view()),
    path("admin/platform/audit/stats", PlatformAuditStatsView.as_view()),
    path("admin/platform/audit/events", PlatformAuditEventsView.as_view()),
    path("admin/platform/audit/export", PlatformAuditExportView.as_view()),
    path("platform/admin/audit/stats", PlatformAuditStatsView.as_view()),
    path("platform/admin/audit/events", PlatformAuditEventsView.as_view()),
    path("platform/admin/audit/export", PlatformAuditExportView.as_view()),
    path("admin/actions/stats", AdminActionStatsView.as_view()),
    path("admin/actions/events", AdminActionEventsView.as_view()),
    path("admin/actions/events/<int:action_id>", AdminActionDetailView.as_view()),
    path("admin/action-center/stats", AdminActionStatsView.as_view()),
    path("admin/action-center/events", AdminActionEventsView.as_view()),
    path("admin/action-center/events/<int:action_id>", AdminActionDetailView.as_view()),
    path("tasks", TasksView.as_view()),
    path("tasks/board", TasksBoardView.as_view()),
    path("tasks/stats", TasksStatsView.as_view()),
    path("tasks/bulk/status", TasksBulkStatusView.as_view()),
    path("tasks/bulk/assign", TasksBulkAssignView.as_view()),
    path("tasks/<int:task_id>/activity", TaskActivityView.as_view()),
    path("tasks/<int:task_id>", TaskDetailView.as_view()),
]
