# Generated by Django 5.2.13 on 2026-04-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_usercapability'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usercapability',
            new_name='identity_us_user_id_364bb1_idx',
            old_name='identity_us_user_id_cap_idx',
        ),
        migrations.RenameIndex(
            model_name='usercapability',
            new_name='identity_us_capabil_ef9710_idx',
            old_name='identity_us_capabil_idx',
        ),
    ]
