# Generated by Django 5.2.13 on 2026-04-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='mock_override',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
