from django.urls import path

from .views import (
    BuildingDepartmentsView,
    BuildingDetailView,
    BuildingsListView,
    EmployeeMeProfileView,
    EmployeeMeNotificationsView,
    EmployeeProfileByIdView,
    EmployeeProfileGlobalAliasView,
    EmployeeProfileView,
    EmployeeWorkspaceCabinetView,
    EmployeeWorkspaceContextView,
    FloorWorkspaceView,
    WorkspaceTaskAliasDetailView,
    WorkspaceTaskAuditView,
    WorkspaceTaskChecklistItemView,
    WorkspaceTaskChecklistView,
    WorkspaceTaskCommentsView,
    WorkspaceTasksAliasView,
    WorkspaceContextAliasView,
    WorkspaceContextGlobalAliasView,
    WorkspaceDocumentLinkView,
    WorkspaceDocumentUploadView,
    WorkspaceQuickTasksView,
    WorkspaceTaskBuildingAuditView,
    WorkspaceTaskBuildingChecklistItemView,
    WorkspaceTaskBuildingChecklistView,
    WorkspaceTaskBuildingCommentsView,
)

urlpatterns = [
    path("buildings", BuildingsListView.as_view(), name="buildings-list"),
    path("buildings/<str:building_id>", BuildingDetailView.as_view(), name="buildings-detail"),
    path(
        "buildings/<str:building_id>/departments",
        BuildingDepartmentsView.as_view(),
        name="buildings-departments",
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/workspace",
        FloorWorkspaceView.as_view(),
        name="workspace-floor",
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/workspace/employee/<str:employee_id>",
        EmployeeWorkspaceContextView.as_view(),
        name="workspace-employee-context",
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/employees/<str:employee_id>/profile",
        EmployeeProfileView.as_view(),
        name="employee-profile",
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/tasks/<str:task_id>/audit",
        WorkspaceTaskBuildingAuditView.as_view(),
        name="workspace-task-building-audit",
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/tasks/<str:task_id>/comments",
        WorkspaceTaskBuildingCommentsView.as_view(),
        name="workspace-task-building-comments",
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/tasks/<str:task_id>/checklist",
        WorkspaceTaskBuildingChecklistView.as_view(),
        name="workspace-task-building-checklist",
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/tasks/<str:task_id>/checklist/<str:item_id>",
        WorkspaceTaskBuildingChecklistItemView.as_view(),
        name="workspace-task-building-checklist-item",
    ),
    path(
        "buildings/<str:building_id>/floors/<str:floor_id>/workspace-context",
        WorkspaceContextAliasView.as_view(),
        name="workspace-context-alias",
    ),
    path(
        "workspace/context",
        WorkspaceContextGlobalAliasView.as_view(),
        name="workspace-context-global-alias",
    ),
    path(
        "employees/<str:employee_id>/profile",
        EmployeeProfileGlobalAliasView.as_view(),
        name="employee-profile-global-alias",
    ),
    path("workspace", EmployeeWorkspaceCabinetView.as_view(), name="workspace"),
    path("workspace/documents/upload", WorkspaceDocumentUploadView.as_view(), name="workspace-documents-upload"),
    path("workspace/documents/link", WorkspaceDocumentLinkView.as_view(), name="workspace-documents-link"),
    path("workspace/tasks", WorkspaceTasksAliasView.as_view(), name="workspace-tasks-alias"),
    path(
        "workspace/tasks/<str:task_id>/audit",
        WorkspaceTaskAuditView.as_view(),
        name="workspace-task-audit-alias",
    ),
    path(
        "workspace/tasks/<str:task_id>/comments",
        WorkspaceTaskCommentsView.as_view(),
        name="workspace-task-comments-alias",
    ),
    path(
        "workspace/tasks/<str:task_id>/checklist",
        WorkspaceTaskChecklistView.as_view(),
        name="workspace-task-checklist-alias",
    ),
    path(
        "workspace/tasks/<str:task_id>/checklist/<str:item_id>",
        WorkspaceTaskChecklistItemView.as_view(),
        name="workspace-task-checklist-item-alias",
    ),
    path(
        "workspace/tasks/<str:task_id>",
        WorkspaceTaskAliasDetailView.as_view(),
        name="workspace-task-detail-alias",
    ),
    path("employees/me", EmployeeMeProfileView.as_view(), name="employees-me"),
    path("employees/me/notifications", EmployeeMeNotificationsView.as_view(), name="employees-me-notifications"),
    path("employees/<str:employee_id>", EmployeeProfileByIdView.as_view(), name="employees-by-id"),
    path("workspace/quick-tasks", WorkspaceQuickTasksView.as_view(), name="workspace-quick-tasks"),
]
