# Generated by Django 5.2.13 on 2026-04-21 13:19

import apps.workspaces.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceCabinetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('document_type', models.CharField(max_length=16)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('external', 'External link')], max_length=16)),
                ('external_href', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.workspaces.models.workspace_cabinet_upload_to)),
                ('owner_label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_cabinet_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
