# Generated by Django 5.2.13 on 2026-04-23 12:57

import django.db.models.deletion
from django.db import migrations, models


def backfill_workspace_upload_sizes(apps, schema_editor):
    Model = apps.get_model("workspaces", "WorkspaceCabinetDocument")
    for obj in Model.objects.filter(source="upload").iterator():
        if getattr(obj, "upload_stored_bytes", 0):
            continue
        f = getattr(obj, "file", None)
        if not f or not getattr(f, "name", None):
            continue
        try:
            sz = int(f.size or 0)
        except OSError:
            sz = 0
        if sz:
            Model.objects.filter(pk=obj.pk).update(upload_stored_bytes=sz)


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storageprovider'),
        ('workspaces', '0001_workspace_cabinet_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacecabinetdocument',
            name='storage_object_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workspacecabinetdocument',
            name='storage_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workspace_cabinet_documents', to='storage.storageprovider'),
        ),
        migrations.AddField(
            model_name='workspacecabinetdocument',
            name='upload_stored_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.RunPython(backfill_workspace_upload_sizes, migrations.RunPython.noop),
    ]
