# Generated by Django 5.2.13 on 2026-04-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_created_7710b7_idx',
            old_name='audit_audit_created_c93543_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_actor_i_58da28_idx',
            old_name='audit_audit_actor_i_fef507_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_event_t_124af2_idx',
            old_name='audit_audit_event_t_6c7f08_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_project_c77a15_idx',
            old_name='audit_audit_project_4df4f4_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_task_id_170366_idx',
            old_name='audit_audit_task_id_ae0a84_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_chat_id_3fcf7e_idx',
            old_name='audit_audit_chat_id_1dc08f_idx',
        ),
    ]
