# Generated by Django 5.2.13 on 2026-04-25 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_scope_type', models.CharField(choices=[('global', 'Global'), ('company', 'Company'), ('department', 'Department'), ('project', 'Project'), ('self', 'Self')], default='global', max_length=32)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='DelegationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(max_length=128)),
                ('from_scope_type', models.CharField(choices=[('global', 'Global'), ('company', 'Company'), ('department', 'Department'), ('project', 'Project'), ('self', 'Self')], max_length=32)),
                ('to_scope_type', models.CharField(choices=[('global', 'Global'), ('company', 'Company'), ('department', 'Department'), ('project', 'Project'), ('self', 'Self')], max_length=32)),
                ('allow_delegate', models.BooleanField(default=True)),
                ('allow_same_scope_only', models.BooleanField(default=False)),
                ('allow_narrower_scope', models.BooleanField(default=True)),
                ('max_delegate_depth', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('permission_code', 'from_scope_type', 'to_scope_type'),
                'indexes': [models.Index(fields=['permission_code'], name='access_dele_permiss_a082f0_idx'), models.Index(fields=['from_scope_type', 'to_scope_type'], name='access_dele_from_sc_182dcf_idx')],
                'constraints': [models.UniqueConstraint(fields=('permission_code', 'from_scope_type', 'to_scope_type'), name='uniq_delegation_rule')],
            },
        ),
        migrations.CreateModel(
            name='PermissionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(choices=[('organization', 'Organization'), ('projects', 'Projects'), ('documents', 'Documents'), ('tasks', 'Tasks'), ('ai', 'AI'), ('access', 'Access'), ('other', 'Other')], default='other', max_length=32)),
                ('allowed_scopes', models.JSONField(blank=True, default=list)),
                ('can_be_delegated', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('module', 'code'),
                'indexes': [models.Index(fields=['module', 'code'], name='access_perm_module_fc32f6_idx'), models.Index(fields=['is_active'], name='access_perm_is_acti_079327_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('grant_created', 'Grant created'), ('grant_updated', 'Grant updated'), ('grant_revoked', 'Grant revoked'), ('grant_expired', 'Grant expired'), ('delegate_created', 'Delegate created'), ('delegate_revoked', 'Delegate revoked'), ('template_assigned', 'Template assigned'), ('template_removed', 'Template removed'), ('definition_updated', 'Permission definition updated'), ('rule_updated', 'Delegation rule updated')], max_length=64)),
                ('permission_code', models.CharField(blank=True, default='', max_length=128)),
                ('scope_type', models.CharField(blank=True, default='', max_length=32)),
                ('scope_id', models.CharField(blank=True, default='', max_length=128)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['target_employee', 'created_at'], name='access_perm_target__97ff76_idx'), models.Index(fields=['actor', 'created_at'], name='access_perm_actor_i_044d9a_idx'), models.Index(fields=['action'], name='access_perm_action_48a627_idx'), models.Index(fields=['permission_code'], name='access_perm_permiss_ce14e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(max_length=128)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('company', 'Company'), ('department', 'Department'), ('project', 'Project'), ('self', 'Self')], default='global', max_length=32)),
                ('scope_id', models.CharField(blank=True, default='', max_length=128)),
                ('grant_mode', models.CharField(choices=[('use_only', 'Use only'), ('use_and_delegate', 'Use and delegate')], default='use_only', max_length=32)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('role_template', 'Role template'), ('delegation', 'Delegation'), ('system_seed', 'System seed')], default='manual', max_length=32)),
                ('source_id', models.CharField(blank=True, default='', max_length=128)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_access_grants', to=settings.AUTH_USER_MODEL)),
                ('parent_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_grants', to='access.permissiongrant')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-granted_at',),
                'indexes': [models.Index(fields=['employee', 'status'], name='access_perm_employe_97095a_idx'), models.Index(fields=['permission_code', 'status'], name='access_perm_permiss_d7cf99_idx'), models.Index(fields=['scope_type', 'scope_id'], name='access_perm_scope_t_047bf9_idx'), models.Index(fields=['parent_grant'], name='access_perm_parent__fce00d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleTemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('company', 'Company'), ('department', 'Department'), ('project', 'Project'), ('self', 'Self')], default='global', max_length=32)),
                ('scope_id', models.CharField(blank=True, default='', max_length=128)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_role_templates', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_role_templates', to=settings.AUTH_USER_MODEL)),
                ('role_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='access.roletemplate')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['employee', 'is_active'], name='access_role_employe_3e016d_idx'), models.Index(fields=['role_template', 'is_active'], name='access_role_role_te_b51705_idx'), models.Index(fields=['scope_type', 'scope_id'], name='access_role_scope_t_3dd493_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleTemplatePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(max_length=128)),
                ('grant_mode', models.CharField(choices=[('use_only', 'Use only'), ('use_and_delegate', 'Use and delegate')], default='use_only', max_length=32)),
                ('default_enabled', models.BooleanField(default=True)),
                ('role_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='access.roletemplate')),
            ],
            options={
                'ordering': ('permission_code',),
                'indexes': [models.Index(fields=['permission_code'], name='access_role_permiss_46dcea_idx')],
                'constraints': [models.UniqueConstraint(fields=('role_template', 'permission_code'), name='uniq_role_template_permission')],
            },
        ),
    ]
