# Generated by Django 5.2.13 on 2026-04-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="delegationrule",
            name="from_scope_type",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("company", "Company"),
                    ("department", "Department"),
                    ("project", "Project"),
                    ("task", "Task"),
                    ("ai_workspace", "AI workspace"),
                    ("module", "Module"),
                    ("self", "Self"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="delegationrule",
            name="to_scope_type",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("company", "Company"),
                    ("department", "Department"),
                    ("project", "Project"),
                    ("task", "Task"),
                    ("ai_workspace", "AI workspace"),
                    ("module", "Module"),
                    ("self", "Self"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="permissiongrant",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("company", "Company"),
                    ("department", "Department"),
                    ("project", "Project"),
                    ("task", "Task"),
                    ("ai_workspace", "AI workspace"),
                    ("module", "Module"),
                    ("self", "Self"),
                ],
                default="global",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="roletemplate",
            name="default_scope_type",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("company", "Company"),
                    ("department", "Department"),
                    ("project", "Project"),
                    ("task", "Task"),
                    ("ai_workspace", "AI workspace"),
                    ("module", "Module"),
                    ("self", "Self"),
                ],
                default="global",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="roletemplateassignment",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("company", "Company"),
                    ("department", "Department"),
                    ("project", "Project"),
                    ("task", "Task"),
                    ("ai_workspace", "AI workspace"),
                    ("module", "Module"),
                    ("self", "Self"),
                ],
                default="global",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PermissionDeny",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("permission_code", models.CharField(max_length=128)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("company", "Company"),
                            ("department", "Department"),
                            ("project", "Project"),
                            ("task", "Task"),
                            ("ai_workspace", "AI workspace"),
                            ("module", "Module"),
                            ("self", "Self"),
                        ],
                        default="global",
                        max_length=32,
                    ),
                ),
                ("scope_id", models.CharField(blank=True, default="", max_length=128)),
                ("denied_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked"), ("expired", "Expired")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("policy", "Policy"), ("system", "System")],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=128)),
                ("note", models.TextField(blank=True)),
                (
                    "denied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_access_denies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_denies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_access_denies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-denied_at",),
                "indexes": [
                    models.Index(fields=["employee", "status"], name="access_perm_employe_9c5b74_idx"),
                    models.Index(fields=["permission_code", "status"], name="access_perm_permiss_89952d_idx"),
                    models.Index(fields=["scope_type", "scope_id"], name="access_perm_scope_t_a2ec54_idx"),
                ],
            },
        ),
    ]
