# Generated by Django 5.2.13 on 2026-04-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('organization', 'Organization'), ('project', 'Project'), ('user', 'User')], default='global', max_length=32)),
                ('scope_id', models.CharField(blank=True, default='', help_text='Empty for global; otherwise organization id, project id, or user id.', max_length=64)),
                ('max_bytes', models.PositiveBigIntegerField()),
                ('warn_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('scope', 'scope_id'),
                'constraints': [models.UniqueConstraint(fields=('scope', 'scope_id'), name='uniq_storage_quota_scope')],
            },
        ),
    ]
