# Generated by Django 5.2.13 on 2026-04-23 12:44

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('s3_compat', 'S3-compatible (MinIO / AWS / …)')], default='s3_compat', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=100)),
                ('endpoint_url', models.CharField(blank=True, help_text='e.g. http://localhost:9000 — empty uses AWS default for the region.', max_length=512)),
                ('bucket', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('use_ssl', models.BooleanField(default=True)),
                ('path_style', models.BooleanField(default=True, help_text='True for most MinIO installs (path-style addressing).')),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('priority', 'code'),
                'constraints': [
                    models.UniqueConstraint(
                        condition=Q(is_default=True),
                        fields=('is_default',),
                        name='uniq_storage_provider_single_default',
                    )
                ],
            },
        ),
    ]
